import type { StoreProduct } from '@/components/store-front/types';

const images = {
    pitcher:
        'https://lh3.googleusercontent.com/aida-public/AB6AXuCZ2KQA0OUADv5QlyKPmxtWxn3vOGv6c1R_zlBwBHF1EA3FuwQc7AptxqMj3jFBoZHU3k3Y1GWE2LOiptGNe1_BlLBwPXDm8l8Ana__G__d_m6Ed8Pk6yzYhUEg7lACK74uY16Jge-5GoBNZqK1IXjQu9XJTRfsGl7dTfMQcz1udH681qONoFWrcE7oUEDi2RcbwPK4DSOldmDEpWK4AneUUmTH8VNbYmlGMEW5Zks7zD92JU6vsK6jiA',
    chawan: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAfD2ht2jbbjZv9UoaFkRbp-OpTWmBpy0KsoZyRhX0lHC9lApR9kWBCLy5S5_4wRPZMrHjO9KqV7hT2Ce0C0YfokZOwcnLx2KFav7oyI8ge043LtSr1EZiP1452_ds4umam57uTeOtb0l9iBNQJOwjOq3iYLamh0sLkE6Qagr8OozC_f2Ar0bczTGmxKQmj_eSFed39Rpvf9xRTuj1noo_4z1iJqoyB2HHBGBpVNheAlgMepuHluLjT6Q',
    digital:
        'https://lh3.googleusercontent.com/aida-public/AB6AXuCD2P6kmA_nyzGZC_hJdVUByv7GW3AdQ2_UbcIDlkl_nPZRpVa-mGRR89_NF1KbpGjLWuYXd-beWpwwa7JGFW7ssWkrrXcva6k8SwttuLEugd2-5vU5ZFC5U1UkuTfzAqhGRyfYIXb2P0LEsTDOG8lYVjb0htM4bCb6wYjvviRMZ8iQsWVFGbV1Ob3ptre0shwOAzosjdnDD3CXs_BGNmxkvZojLcadCxq3gw561gtEcQELyJwRACbtRg',
    workshop:
        'https://lh3.googleusercontent.com/aida-public/AB6AXuBsdtPbKb6LL0uuyeFGGkG2fE8eATANGC6iwcjVcAk5b0Hrm8vb2xV65a6HnlJvqgk21DuGPGeHLKbHFDilYAK0uXUu4gOD11hdOyN9jaw1tRhfPu9ZCDmtfjsqhLsDYAs7g5saPqvMjxKiz1PYbD78UNSU0M6TgG2B6p_7NEXZFXpYCaGDPhE1AEJI-mL1mE4A_qNwr6BxGeahnkUcpo11qoOBy6k-hUXi22fDnkGQcBY6x4jnBe_nAA',
};

export const storeImages = images;

export const products: StoreProduct[] = [
    {
        id: 'jarra',
        category: 'physical',
        isLimited: true,
        title: 'Jarra Escultórica en Gres',
        detail: 'Torno manual · Pieza única',
        description: 'Colección Ceniza & Arcilla (750ml)',
        price: 28000,
        popularity: 95,
        availability: 'Stock: 2 unidades',
        image: images.pitcher,
    },
    {
        id: 'chawan',
        category: 'physical',
        isLimited: true,
        title: 'Cuenco Chawan Ceremonia',
        detail: 'Gres de alta · Chamota fina',
        description: 'Forma kurinuki y desbastado rítmico',
        price: 22000,
        popularity: 98,
        availability: 'Stock: 4 unidades',
        image: images.chawan,
    },
    {
        id: 'espresso',
        category: 'physical',
        isLimited: false,
        title: 'Dúo Tazas Espresso Cordillera',
        detail: 'Set x2 · Arcilla roja local',
        description: '80ml ideales para extracciones intensas',
        price: 18000,
        popularity: 88,
        availability: 'Stock: 6 sets',
        image: images.pitcher,
    },
    {
        id: 'plato',
        category: 'physical',
        isLimited: false,
        title: 'Plato Trinche Huella Volcánica',
        detail: 'Diámetro 26cm · Alta resistencia',
        description: 'Esmaltado mineral mate, apto lavavajillas',
        price: 24500,
        popularity: 80,
        availability: 'Stock: 5 unidades',
        image: images.chawan,
    },
    {
        id: 'jarron',
        category: 'physical',
        isLimited: true,
        title: 'Jarrón Botánico Monolito',
        detail: 'Alto 32cm · Modelado en placas',
        description: 'Textura erosionada inspirada en los basaltos',
        price: 36000,
        popularity: 92,
        availability: 'Última pieza disponible',
        image: images.pitcher,
    },
    {
        id: 'guia',
        category: 'digital',
        isLimited: false,
        title: 'Guía: Técnicas y Fórmulas',
        detail: 'Manual descargable · PDF de 78 págs',
        description: 'Recetario completo de esmaltes de ceniza',
        price: 14500,
        popularity: 99,
        availability: 'Descarga instantánea',
        image: images.digital,
    },
    {
        id: 'masterclass',
        category: 'digital',
        isLimited: false,
        title: 'Masterclass: El Torno Sensitivo',
        detail: 'Curso en video 4K · 3.5 horas',
        description: 'Centrado, paredes delgadas y ritmo respiratorio',
        price: 26000,
        popularity: 91,
        availability: 'Acceso de por vida',
        image: images.digital,
    },
    {
        id: 'bitacora',
        category: 'digital',
        isLimited: false,
        title: 'Bitácora de Control de Hornadas',
        detail: 'Plantilla Notion & Sheets',
        description: 'Registro de curvas térmicas, conos y resultados',
        price: 9500,
        popularity: 75,
        availability: 'Descarga instantánea',
        image: images.digital,
    },
    {
        id: 'mortero',
        category: 'physical',
        isLimited: false,
        title: 'Mortero Suribachi de Semillas',
        detail: 'Tipo Suribachi · Gres rugoso',
        description: 'Ranurado interior a mano para molienda en seco',
        price: 21000,
        popularity: 83,
        availability: 'Stock: 3 unidades',
        image: images.chawan,
    },
    {
        id: 'taza',
        category: 'physical',
        isLimited: false,
        title: 'Taza Ritual del Bosque',
        detail: 'Capacidad 320ml · Asa ergonómica',
        description: 'Tacto suave y retención prolongada de calor',
        price: 16500,
        popularity: 94,
        availability: 'Stock: 7 unidades',
        image: images.pitcher,
    },
    {
        id: 'nido',
        category: 'physical',
        isLimited: false,
        title: 'Nido de Cuencos Anidados',
        detail: 'Set de 4 cuencos anidados',
        description: 'Desde 10cm hasta 22cm de diámetro para servicio',
        price: 38000,
        popularity: 79,
        availability: 'Stock: 2 sets',
        image: images.chawan,
    },
    {
        id: 'incienso',
        category: 'physical',
        isLimited: true,
        title: 'Porta-Incienso Caudal',
        detail: 'Modelado en barra de gres',
        description: 'Canal colector de cenizas y base antideslizante',
        price: 12000,
        popularity: 85,
        availability: 'Stock: 8 unidades',
        image: images.pitcher,
    },
];
